/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SkillGroup = {
  _id: string;
  _type: "skillGroup";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  category?: string;
  techStack?: Array<
    {
      _key: string;
    } & TechStack
  >;
  icon?: "layers" | "paintBrush" | "cpu" | "zap" | "globe" | "wrench";
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  tagline?: string;
  description?: string;
  techStack?: Array<
    {
      _key: string;
    } & TechStack
  >;
  metrics?: Array<
    {
      _key: string;
    } & Metric
  >;
  featured?: boolean;
  repositoryUrl?: string;
  demoUrl?: string;
  order?: number;
};

export type Experience = {
  _id: string;
  _type: "experience";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  employer?: string;
  jobTitle?: string;
  startDate?: string;
  endDate?: string;
  location?: string;
  current?: boolean;
  description?: string;
  achievements?: Array<string>;
  techStack?: Array<
    {
      _key: string;
    } & TechStack
  >;
};

export type TechStack = {
  _type: "techStack";
  title?: string;
};

export type Metric = {
  _type: "metric";
  title?: string;
  value?: number;
  suffix?: string;
  label?: string;
  sub?: string;
};

export type Differential = {
  _id: string;
  _type: "differential";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  metric?: string;
  icon?: "target" | "layers" | "barChart" | "users";
};

export type SocialLink = {
  _type: "socialLink";
  platform?: "github" | "linkedin" | "twitter" | "other";
  label?: string;
  url?: string;
};

export type Profile = {
  _id: string;
  _type: "profile";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  firstName?: string;
  lastName?: string;
  jobTarget?: string;
  headline?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  email?: string;
  phone?: string;
  location?: string;
  country?: string;
  available?: boolean;
  socialLinks?: Array<
    {
      _key: string;
    } & SocialLink
  >;
  metrics?: Array<
    {
      _key: string;
    } & Metric
  >;
  techStack?: Array<
    {
      _key: string;
    } & TechStack
  >;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type AllSanitySchemaTypes =
  | SkillGroup
  | Project
  | Experience
  | TechStack
  | Metric
  | Differential
  | SocialLink
  | Profile
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityImageHotspot
  | SanityImageCrop
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
  | Slug;

// Source: ../portfolio/src/lib/sanity/queries.ts
// Variable: PROFILE_QUERY
// Query: *[_type == "profile"][0]{_id, title, firstName, lastName, jobTarget, headline, email, phone, available, socialLinks, metrics, techStack}
export type PROFILE_QUERY_RESULT = {
  _id: string;
  title: string | null;
  firstName: string | null;
  lastName: string | null;
  jobTarget: string | null;
  headline: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  email: string | null;
  phone: string | null;
  available: boolean | null;
  socialLinks: Array<
    {
      _key: string;
    } & SocialLink
  > | null;
  metrics: Array<
    {
      _key: string;
    } & Metric
  > | null;
  techStack: Array<
    {
      _key: string;
    } & TechStack
  > | null;
} | null;

// Source: ../portfolio/src/lib/sanity/queries.ts
// Variable: DIFFERENTIALS_QUERY
// Query: *[_type == "differential"] | order(order asc) {_id, title, description, metric, icon}
export type DIFFERENTIALS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  description: string | null;
  metric: string | null;
  icon: "barChart" | "layers" | "target" | "users" | null;
}>;

// Source: ../portfolio/src/lib/sanity/queries.ts
// Variable: EXPERIENCES_QUERY
// Query: *[_type == "experience"] | order(order asc) {_id, jobTitle, employer, startDate, endDate, current, description, location, achievements, techStack, order}
export type EXPERIENCES_QUERY_RESULT = Array<{
  _id: string;
  jobTitle: string | null;
  employer: string | null;
  startDate: string | null;
  endDate: string | null;
  current: boolean | null;
  description: string | null;
  location: string | null;
  achievements: Array<string> | null;
  techStack: Array<
    {
      _key: string;
    } & TechStack
  > | null;
  order: null;
}>;

// Source: ../portfolio/src/lib/sanity/queries.ts
// Variable: PROJECTS_QUERY
// Query: *[_type == "project"] | order(order asc) {_id, name, slug, tagline, description, techStack, metrics, featured, repositoryUrl, liveUrl, order}
export type PROJECTS_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  slug: null;
  tagline: string | null;
  description: string | null;
  techStack: Array<
    {
      _key: string;
    } & TechStack
  > | null;
  metrics: Array<
    {
      _key: string;
    } & Metric
  > | null;
  featured: boolean | null;
  repositoryUrl: string | null;
  liveUrl: null;
  order: number | null;
}>;

// Source: ../portfolio/src/lib/sanity/queries.ts
// Variable: SKILL_GROUPS_QUERY
// Query: *[_type == "skillGroup"] | order(order asc) {_id, category, techStack, icon}
export type SKILL_GROUPS_QUERY_RESULT = Array<{
  _id: string;
  category: string | null;
  techStack: Array<
    {
      _key: string;
    } & TechStack
  > | null;
  icon: "cpu" | "globe" | "layers" | "paintBrush" | "wrench" | "zap" | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "profile"][0]{_id, title, firstName, lastName, jobTarget, headline, email, phone, available, socialLinks, metrics, techStack}': PROFILE_QUERY_RESULT;
    '*[_type == "differential"] | order(order asc) {_id, title, description, metric, icon}': DIFFERENTIALS_QUERY_RESULT;
    '*[_type == "experience"] | order(order asc) {_id, jobTitle, employer, startDate, endDate, current, description, location, achievements, techStack, order}': EXPERIENCES_QUERY_RESULT;
    '*[_type == "project"] | order(order asc) {_id, name, slug, tagline, description, techStack, metrics, featured, repositoryUrl, liveUrl, order}': PROJECTS_QUERY_RESULT;
    '*[_type == "skillGroup"] | order(order asc) {_id, category, techStack, icon}': SKILL_GROUPS_QUERY_RESULT;
  }
}
