'use client'

import React, { ReactNode } from 'react'

import { AnimatePresence } from 'framer-motion'
import { Montserrat } from 'next/font/google'

import { Footer } from './Footer'
import { Header } from './Header'

import './globals.css'

const montserrat = Montserrat({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" className={montserrat.className}>
      <body className="bg-light dark:bg-dark w-full min-h-screen">
        <Header />
        <AnimatePresence mode="wait">{children}</AnimatePresence>
        <Footer />
      </body>
    </html>
  )
}
