import "../globals.css";

import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { getMessages, setRequestLocale } from "next-intl/server";
import { notFound } from "next/navigation";

import { fontSans } from "@/config/fonts";
import { routing } from "@/i18n/routing";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

type LocaleLayoutProps = Readonly<{
	children: React.ReactNode;
	params: Promise<{ locale: string }>;
}>;

export function generateStaticParams() {
	return routing.locales.map((locale) => ({ locale }));
}

export default async function LocaleLayout(props: LocaleLayoutProps) {
	const { children, params } = props;
	const locale = (await params).locale;

	// Ensure that the incoming `locale` is valid
	// biome-ignore lint/suspicious/noExplicitAny: <explanation>
	if (!routing.locales.includes(locale as any)) {
		notFound();
	}

	// Providing all messages to the client
	// side is the easiest way to get started
	const messages = await getMessages();

	// Enable static rendering
	setRequestLocale(locale);

	return (
		<html lang={locale}>
			<body className={`${fontSans.variable} antialiased`}>
				<NextIntlClientProvider messages={messages}>
					{children}
				</NextIntlClientProvider>
			</body>
		</html>
	);
}
